# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: 
  push: # Run jobs when a push is detected
    branches: [ "main", "Sprint#*" ]
  pull_request: # Run jobs when a pull request is detected
    branches: [ "main", "Sprint#*" ]

jobs:
  end-to-end_testing:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: ${{ vars.PORT }}

    steps:
    - name: Install Chrome/Chromium and ChromeDriver
      uses: browser-actions/setup-chrome@v1 # Uses the version 1 of setup-chrome action
      with:
        chrome-version: 131.0.6778.69
        install-chromedriver: true
        install-dependencies: true

    - name: Checkout Source Code 
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci # Install dependencies based on what's inside package-lock.json

    - name: Run Tests
      run: npm run ci

  unit_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm run test-jest