name: Node.js CI

on: 
  push:
    branches: [ "main", "Sprint#*" ]
  pull_request:
    branches: [ "main", "Sprint#*" ]

jobs:
  end-to-end_testing:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: 5000

    steps:
    - name: Install Chrome/Chromium and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 131.0.6778.69
        install-chromedriver: true
        install-dependencies: true

    - name: Checkout Source Code 
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run End-to-End Tests
      run: npm run ci

  unit_testing:
    runs-on: ubuntu-latest

    env:
      PORT: 6000

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm run test-jest
