# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "Sprint#*" ]
  pull_request:
    branches: [ "main", "Sprint#*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Chrome
      run: |
        sudo apt-get purge google-chrome-stable
        sudo wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_97.0.4692.71-1_amd64.deb && \
        sudo dpkg -i google-chrome-stable_97.0.4692.71-1_amd64.deb && \
        sudo apt-mark hold google-chrome-stable
    - name: Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/97.0.4692.71/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip chromedriver -d /usr/local/bin
    - run: npm ci
    - run: npm run build --if-present
    - name: Run tests
      run: npm test